# Generated by Django 6.1 on 2026-08-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('BEBIDA', 'Bebida'), ('ALIMENTO', 'Alimento'), ('POSTRE', 'Postre')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
